project_id = "qownsvcdfguwpdmepsvg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54326

[analytics]
enabled = true
port = 54327

[functions.auto-report-scheduler]
verify_jwt = false

[functions.clover-sales]
verify_jwt = true

[functions.clover-shop-info]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = false

[functions.email-commission-report]
verify_jwt = false

[functions.manage-cron-jobs]
verify_jwt = false

[functions.daily-sales-sync]
verify_jwt = false